export type Product = {
  id: number
  name: string
  description: string
  price: string
  category: string
  image: string
}

export const products: Product[] = [
  {
    id: 1,
    name: "Gerberas",
    description: "Gerberas en tonos mix, 6 Geberas $320, 12 Gerberas $600, 20 Gerberas $850.",
    price: "$320 - $850",
    category: "Ramos",
    image: "/productos/gerberamix.png",
    // image: "../../public/productos/gerbera mix.png",
  },
  {
    id: 2,
    name: "Hermoso Cariño",
    description: "El mix ideal 50 Rosas en colores (rosa, rojas y blancas) 6 Gerberas.",
    price: "$1850",
    category: "Ramos",
    image: "/productos/hermosocariño.png",
  },
  {
    id: 3,
    name: "Bouquets de Rosas",
    description: "Ramo de rosas con colores a elegir: rojas, rosas, rosa fiusha, blancas, lila, amarillo. 12 Rosas $450, 24 Rosas $850, 50 Rosas $1680, 75 rosas $2350, 100 rosas $3000.",
    price: "$450 - $3000",
    category: "Ramos",
    image: "/productos/bouquets1.png",
  },
  {
    id: 4,
    name: "50 Gerberas",
    description: "50 gerberas en tonos rosas, ramo grande con aprox 50 cm de diámetro puede llevar decoración de papel seda o mallita aperlada. Liston personalizado.\nElige en forma circular o de corazón tu ramo.",
    price: "$2100",
    category: "Ramos",
    image: "/productos/gerbera50-1.png",
  },
  {
    id: 5,
    name: "Tulipanes",
    description: "Bouquets de tulipanes 5 Tulipanes $800 10 tulipanes $1,300 20 Tulipanes $2,300\n30 Tulipanes $3,500\n50 Tulipanes $5,500.",
    price: "$800 - $5500",
    category: "Ramos",
    image: "/productos/tulipanes1.png",
  },
  {
    id: 6,
    name: "Arreglo florales",
    description: "arreglo floral con margaritas en\nbase de madera ideal\npara las amantes de esta flor ten por\nseguro que tu arreglo durará... caja mide aprox 40 cm de diámetro.",
    price: "$800",
    category: "Ramos",
    image: "/productos/arreglos1.png",
  },
  {
    id: 7,
    name: "Arreglo florales premium",
    description: "arreglo elegante en base de cerámica con flores premium: 5 Tulipanes, hortensias, gerberas, gerberas pompón, rosas, Rosas inglesas, mini rosas, lisianthus,mathiola, limonium, silver, eucalipto. contiene 45 tallos aprox.",
    price: "$3100",
    category: "Ramos",
    image: "/productos/arreglos2.png",
  },
  {
    id: 8,
    name: "Girasoles Coquette",
    description: "lleva 6 girasoles en forma de flor, claveles tonos rosas alrededor y toques de margaritas.\nAgrega+ $35 un listo con frase para acompañar tu\nramo.",
    price: "$590",
    category: "Ramos",
    image: "/productos/girasoles1.png",
  },
  {
    id: 9,
    name: "Girasoles Románticos",
    description: "lleva 6 girasoles en forma\n    de flor, 12 rosas Rojas + follaje en tono verde. agrega +55 corona\ndecorativa.",
    price: "$680",
    category: "Ramos",
    image: "/productos/girasoles2.png",
  },
  {
    id: 10,
    name: "Diseño especial",
    description: "Duo san Valentí ramo con una perfecta combinación rojo y rosa, variedad de flores premium: 12 rosas en técnica reflex, 3 Tulipanes, 1 anturio, Gerberas, margaritas, lisianthus, claveles y perritos.",
    price: "$1200",
    category: "Ramos",
    image: "/productos/especial1.png",
  },
  {
    id: 11,
    name: "Ramos surtiditos",
    description: "No contiene una composición específica de tipo de flor, se arman bajo stock, llenitos de colores vibrantes, variedad de flores, surtiditos bonitos. Papel bajo disponibilidad y conforme a su armado. $700\n$500\n$350\ntamaño grande\nTamaño mediano\nTamaño chico",
    price: "$350 - $700",
    category: "Ramos",
    image: "/productos/surtidos1.png",
  },
  {
    id: 12,
    name: "Termos Stanley",
    description: "Flores con colorimetria a\nbase del termo\nflores mix: Gerberas, claveles, margaritas, rosas y lisianthus. colores disponibles en termos: rosa negro azul lila beige",
    price: "$750",
    category: "Productos",
    image: "/productos/termo2.png",
  },
  {
    id: 13,
    name: "Arreglo en corazon",
    description: "Caja de corazón con tapa personalizada en vinil contiene: 10 rosas aprox y caja de 16 ferreros, listón alrededor y mariposas.",
    price: "$900",
    category: "Productos",
    image: "/productos/arregloscora.png",
  },
  {
    id: 14,
    name: "Osito corazoncito",
    description: "Osito tierno y esponjocito mide 25 cm súper suavecito.",
    price: "$200",
    category: "Productos",
    image: "/productos/ositos2.png",
  },
  {
    id: 15,
    name: "Oso Pomposo",
    description: "Oso relleno de amor mide\n120 cm de alto textura\nsuave.",
    price: "$1580",
    category: "Productos",
    image: "/productos/ositos1.png",
  },
  {
    id: 16,
    name: "Mega Oso",
    description: "El osito de sus sueños... Mega oso mide 1.5 m ideal para sorprender en un día tan especial textura suave.",
    price: "$1800",
    category: "Productos",
    image: "/productos/ositos3.png",
  },
  {
    id: 17,
    name: "Regalo especial",
    description: "Globo san Valentin\n    Chocolates\nosito\nRosas\ncontiene 12 rosas aprox, gypso, base de madera, peluche 25 cm\ncaja de ferreros y globo.",
    price: "$1000",
    category: "Productos",
    image: "/productos/especial2.png",
  },
  {
    id: 18,
    name: "Bouquet de Lirios",
    description: "Lilis 2 tallos, 6 Rosas, 4 Gerberas, perritos y\ncrisantemos.",
    price: "$680",
    category: "Ramos",
    image: "/productos/lirios1.png",
  },
  {
    id: 19,
    name: "Jarron",
    description: "Arreglo en jarrón, 2 tallos de lilis, lisianthus, gerberas, rosas, perritos y follajes..",
    price: "$730",
    category: "Ramos",
    image: "/productos/lirios2.png",
  },
  {
    id: 20,
    name: "Diseño unico Tonos pasteles",
    description: "Flores en tonos lilas un mix ideal lleva Gerberas, lisianthus, Roxanas, margaritas, Aquilea, claveles, perritos",
    price: "$680",
    category: "Ramos",
    image: "/productos/unicos1.png",
  },
]
