export type Product = {
  id: number
  name: string
  description: string
  price: string
  category: string
  image: string
}

export const products: Product[] = [
  {
    id: 1,
    name: "Gerberas Mix",
    description: "Ramo de gerberas en tonos mixtos. Disponible en 6, 12 o 20 flores.",
    price: "$320 - $850",
    category: "Ramos",
    image: "/productos/gerberamix.png",
  },
  {
    id: 2,
    name: "Hermoso Cariño",
    description: "50 rosas en tonos rojo, rosa y blanco con 6 gerberas decorativas.",
    price: "$1850",
    category: "Ramos",
    image: "/productos/hermosocariño.png",
  },
  {
    id: 3,
    name: "Bouquet de Rosas",
    description: "Rosas a elegir en distintos colores. Opciones de 12 hasta 100 rosas.",
    price: "$450 - $3000",
    category: "Ramos",
    image: "/productos/bouquets1.png",
  },
  {
    id: 4,
    name: "50 Gerberas Premium",
    description: "Gran ramo de 50 gerberas con decoración y listón personalizado.",
    price: "$2100",
    category: "Ramos",
    image: "/productos/gerbera50-1.png",
  },
  {
    id: 5,
    name: "Tulipanes",
    description: "Bouquets de 5 a 50 tulipanes en presentación elegante.",
    price: "$800 - $5500",
    category: "Ramos",
    image: "/productos/tulipanes1.png",
  },
  {
    id: 6,
    name: "Arreglo Floral",
    description: "Arreglo con margaritas en base de madera. Duradero y elegante.",
    price: "$800",
    category: "Ramos",
    image: "/productos/arreglos1.png",
  },
  {
    id: 7,
    name: "Arreglo Premium",
    description: "Base de cerámica con flores premium y 45 tallos aproximadamente.",
    price: "$3100",
    category: "Ramos",
    image: "/productos/arreglos2.png",
  },
  {
    id: 8,
    name: "Girasoles Coquette",
    description: "6 girasoles con claveles rosas y detalles decorativos.",
    price: "$590",
    category: "Ramos",
    image: "/productos/girasoles1.png",
  },
  {
    id: 9,
    name: "Girasoles Románticos",
    description: "6 girasoles y 12 rosas rojas con follaje decorativo.",
    price: "$680",
    category: "Ramos",
    image: "/productos/girasoles2.png",
  },
  {
    id: 10,
    name: "Diseño Especial",
    description: "Ramo premium con rosas, tulipanes, anturio y flores surtidas.",
    price: "$1200",
    category: "Ramos",
    image: "/productos/especial1.png",
  },
  {
    id: 11,
    name: "Ramo Surpresa",
    description: "Ramo surtido con flores de temporada y colores vibrantes.",
    price: "$350 - $700",
    category: "Ramos",
    image: "/productos/surtidos1.png",
  },
  {
    id: 12,
    name: "Termo Floral",
    description: "Flores mixtas en termo Stanley disponible en varios colores.",
    price: "$750",
    category: "Productos",
    image: "/productos/termo2.png",
  },
  {
    id: 13,
    name: "Arreglo en Corazón",
    description: "Caja en forma de corazón con rosas y ferreros decorados.",
    price: "$900",
    category: "Productos",
    image: "/productos/arregloscora.png",
  },
  {
    id: 14,
    name: "Osito Corazoncito",
    description: "Osito suave de 25 cm ideal para complementar tu regalo.",
    price: "$200",
    category: "Productos",
    image: "/productos/ositos2.png",
  },
  {
    id: 15,
    name: "Oso Pomposo",
    description: "Oso gigante de 120 cm con textura súper suave.",
    price: "$1580",
    category: "Productos",
    image: "/productos/ositos1.png",
  },
  {
    id: 16,
    name: "Mega Oso",
    description: "Impresionante oso de 1.5 m perfecto para sorprender.",
    price: "$1800",
    category: "Productos",
    image: "/productos/ositos3.png",
  },
  {
    id: 17,
    name: "Regalo Especial",
    description: "Incluye rosas, chocolates, peluche y globo decorativo.",
    price: "$1000",
    category: "Productos",
    image: "/productos/especial2.png",
  },
  {
    id: 18,
    name: "Bouquet de Lirios",
    description: "Combinación de lirios, rosas, gerberas y crisantemos.",
    price: "$680",
    category: "Ramos",
    image: "/productos/lirios1.png",
  },
  {
    id: 19,
    name: "Arreglo en Jarrón",
    description: "Arreglo elegante en jarrón con flores mixtas.",
    price: "$730",
    category: "Ramos",
    image: "/productos/lirios2.png",
  },
  {
    id: 20,
    name: "Tonos Pasteles",
    description: "Arreglo en tonos lilas y suaves con flores premium.",
    price: "$680",
    category: "Ramos",
    image: "/productos/unicos1.png",
  },
]
